### ISSUE TITLE
[owpreproc] Normalize by attribute

### ISSUE THREAD

**Issue by stuart-cls** [markotoplak/orange-infrared#13]
Issue to track remaining problem with #12 (Normalization Preprocessor)

Stuart:
> Another thing we need to do with this widget is normalize to a meta attribute, for example scaling by a weight percent to correct for KBr pellet thickness. I was unable to figure out a good way of filling a combo box with the meta/class attributes of the data, since the BaseEditor isn't aware of what data is connected to it as far as I can tell. Help?

Marko:
> I got your question, but I do not have a good answer now. It is also connected with smart filewise limits that would come in handy for default values.

**Comment by markotoplak** [comment]
I implemented setting limits according to the data for cut in the last commit (59776175d3a34e60bdeaf118bdbc9779afd23035).

In short, if an editor implements set_preview_data method then the preview data at that stage is passed to the editor. Before setting defaults in the Cut editor I also had to check whether changes were already made by the user because we do not want to override them.

I think you could fill in your combo box nicely within this function. The data at its input can be sampled but the domain is always the same.

**Comment by stuart-cls** [comment]
Great! I will work on this next.

**Comment by stuart-cls** [comment]
This is ready for review/merge, but commits are built on #18 so I am waiting for that PR to be resolved.
