### ISSUE TITLE
Preprocess widget real estate

### ISSUE THREAD

**Issue by borondics** [markotoplak/orange-infrared#27]
In the preprocessing widget the "real estate" is not so well balanced. 

The left and right panels should be skinnier _(although the preprocessor titles are already too long <- this can be fixed with tooltips displaying a longer description upon mouse-over)_ and the spectrum display wider. Also, I think there should be a bottom and top half for the spectrum display (before/after). Maybe add a toggle functionality (before only, before/after, after only). 

Buttons on the spectrum display itself and/or keyboard shortcuts?

**Comment by markotoplak** [comment]
I suggest redisign of the widget so that currently used preprocessors and their settings are on the left. The available preproprocessors can be shown in a menu that opens after a click on a button. In this way the widget would only need two panes: proprocessor setting pane on the left and a preview pane on the right.

**Comment by markotoplak** [comment]
I have temporarily put settings to the left. I think this is the way to go. What do you think, @borondics ?

**Comment by borondics** [comment]
It is looking better!

One thing though:

 The left panel is defined to be to wide... is it the length of the names
of the preprocessors?

[image: Inline image 1]

The little dot in the middle only toggles it, can't resize at all.

**Comment by scott-cls** [comment]
I really think the pull-down menu should be buttons.  Giving users one click access compared to two click access.  

Also, it might be good if the spectrum display auto-scales after changes are made in the preprocessor settings.

But I am liking where it is going Marco - looks great!

**Comment by markotoplak** [comment]
@borondics Yes, resizable left panel would be useful in this case. Thanks!

@scott-cls To get more screen real estate you have to make some functions less accessible. Because adding preprocessors is a task that is rarely used compared to changing their settings, I believe an additional click is OK. If the preprocessors were buttons, their descriptions would have to be shorter or in the worst case they would become icons (which are often not easily recognizable for new users).

**Comment by stuart-cls** [comment]
Actually, the drop-down selector for preprocessors is great. The problem Scott was talking about is the new controls for the Curves viewer (which is also used in the preprocessor widget).

-Stuart

________________________________

**Comment by scott-cls** [comment]
@markotoplak Sorry for the confusion, but yes I was referring to the pull-down list that @stuart-cls mentioned.

**Comment by markotoplak** [comment]
@scott-cls @stuart-cls Ok, now I get it. Thanks!

I think something even faster are keyboard shortcuts. So for now, if you click that drop down button you can see keyboard shortcuts equivalent to clicks.

**Comment by borondics** [comment]
For the keyboard shortcuts we could implement the GMail style overlay
display at some point, so it is not a hidden feature. Maybe even core
Orange will pull it from us! :)

**Comment by scott-cls** [comment]
@markotoplak - I agree that the keyboard shortcuts are faster, but I really think we should still have one-click buttons on the graph.  Most users are going to navigate around an Orange canvas using their mouse - keeping that style helps in the work flow, teaching, presentations, etc...   

My thoughts anyway.

**Comment by borondics** [comment]
I agree that we have to have the preprocessing functions available on the
screen. How about a small "paradigm shift" and adding the preprocessors as
buttons (either icons or first just text) as an overlay on top of the graph
(like the A that appears to autoscale)? There could be a mouse-over action
that shows the buttons... This way the interface stays clean and we can
also make it easily understandable.
