### ISSUE TITLE
interp1d, extrapolate: necessary? or update scipy requirements

### ISSUE THREAD

**Issue by stuart-cls** [markotoplak/orange-infrared#46]
@markotoplak, 

scipy.interpolate.interp1d(fill_value="extrapolate") used in the revamped version of the rubberband baseline subtraction preprocessor was only added in version 0.17 of scipy.

(Line 192 of `/orangecontrib/infrared/preprocess.py`)

However, I was looking at how it is used, and I'm not sure why we need to specify a fill_value. The convex_hull (or if that fails, np.zeros) should always have a vertex at the extremes of the data and extrapolation should never be necessary. What am I missing?

**Comment by markotoplak** [comment]
Stuart, you are right, extrapolate was unnecessary. 

In some cases (after previous domain conversion - usually interpolation), when edges of data are NaN, the convex hull does not include the data endpoints. We need to replace them with something so that interpolation does not crash - and any value is OK, since the corresponding entries is row are NaN and subtraction result is therefore NaN anyway. I modified the code so that it replaces the edges with NaN in such cases and does not use extrapolate. Thank you!

**Comment by markotoplak** [comment]
If I just removed extrapolate then "test_slightly_different_domain" in test_conversion.py failed. :)

**Comment by stuart-cls** [comment]
Great, I like the solution 👍 Tests pass on my Windows install now. (Except#48)

**Comment by stuart-cls** [comment]
@markotoplak This issue is hitting our users now (they are mostly on Windows as well), could you do a small release to pypi that fixes it?
Thanks,
Stuart

**Comment by markotoplak** [comment]
Updated. Tests pass on my machine with current release and master branch. I
hope it works for you.

Thanks,
Marko

**Comment by stuart-cls** [comment]
Works for my user now! Thanks :)
