### ISSUE TITLE
Score Plots in Scatter plot Crashes

### ISSUE THREAD

**Issue by GioB81** [markotoplak/orange-infrared#71]
When scoring PC scatter plot, often the "score plot" function freezes or at 1% or after at 100% and you cannot do anything but restart Orange.
this happens on Windows, with Anaconda and Orange 3.4.2 

![image](https://cloud.githubusercontent.com/assets/19801152/26678190/a747292a-46cf-11e7-9021-59b2243e10ae.png)

**Comment by markotoplak** [comment]
There is a problem on some platforms with vizrank, because there are some differences how the threading works. The attempted fix (which solves problems for Ubuntu 14.04 with PyQt4) is here: https://github.com/biolab/orange3/pull/2389

Could you please test it by replacing your Orange/widgets/visualize/utils/__init__.py (with Orange 3.4.2+) with http://193.2.72.57/__init__.py

Thanks you!

**Comment by GioB81** [comment]
yes it works...

Thanks!

**Comment by markotoplak** [comment]
Orange 3.4.4, which fixes the issue, is released.
