### ISSUE TITLE
data.py import error

### ISSUE THREAD

**Issue by borondics** [markotoplak/orange-infrared#84]
data.py has this line `from .pymca5 import OmnicMap` but it is not in the installation requirements I think, so it will never load the few Omnic fiels we could.

I get this when I try to run from PyCharm:
```
.../orange-infrared/orangecontrib/infrared/data.py
Traceback (most recent call last):
.../orange-infrared/orangecontrib/infrared/data.py", line 18, in <module>
    from .pymca5 import OmnicMap
ModuleNotFoundError: No module named '__main__.pymca5'; '__main__' is not a package

Process finished with exit code 1
```

**Comment by markotoplak** [comment]
This is normal. That file is not in requirements because it is included.

What happens here is that you can not directly run a script with relative imports. I guess you would like to test some code in this module. I would suggest you write a unit test (see already existing tests) and test your code through that. The other option is to just create a temporary script that uses the code in data.py. 

If you really need to run data.py, you can run it with "python -m orangecontrib.infrared.data".
